-- ───────────────────────────────────────────────────────────────────
-- 20260707_suppliers.sql — Import & enrichissement de l'annuaire fournisseurs.
-- Source : « Liste_des_fournisseurs.xlsx » (Service Comptabilité Astorya).
-- La table `suppliers` existe déjà (sql/20260615_stock_catalogue.sql) ; on
-- enrichit ici les colonnes payment_terms + data jsonb avec, pour chaque
-- fournisseur :
--   data.cost_bracket     répartition par coûts annuels (+50 000€ … -5 000€)
--   data.importance       niveau (strategique / important / standard / secondaire)
--   data.importance_note  note 2..5 (dérivée du volume d'achat, éditable)
--   data.account_number   n° de compte comptable (401…)
--   data.payment_type     type de paiement (prélèvement / virement / carte…)
--   data.invoice_mailbox  où récupérer / faire router la facture
--   data.tva_intracom     TVA intracom mentionnée sur les factures
-- Idempotent : ON CONFLICT (name) DO UPDATE fusionne le jsonb (data || EXCLUDED.data),
-- ne recrée pas les fournisseurs existants et préserve leur catégorie/contacts.
-- RLS déjà posée sur `suppliers` par la migration stock_catalogue.
-- ───────────────────────────────────────────────────────────────────

INSERT INTO suppliers(id, name, payment_terms, data) VALUES
  ('SUP-DEDIBOX', 'DEDIBOX', 'immédiat', '{"cost_bracket": "+50 000€", "importance": "strategique", "importance_note": 5, "account_number": "401DED", "payment_type": "prélèvement et virement", "invoice_mailbox": "telechargement via leur site , factures a telecharger , voir sur la boite mail contact , demander une redirection vers boite mail facture, contacter le commercial et lui demander à passer à 30 jours  prendre les codes aupres de laurent - aller chercher les factures à la main", "tva_intracom": "275"}'::jsonb),
  ('SUP-ACTUALSYSTEMES', 'ACTUAL SYSTEMES', '30 jours', '{"cost_bracket": "+50 000€", "importance": "strategique", "importance_note": 5, "payment_type": "prélèvement", "invoice_mailbox": "facture", "tva_intracom": "290"}'::jsonb),
  ('SUP-TDSYNNEX', 'TD SYNNEX', '30 jours', '{"cost_bracket": "+50 000€", "importance": "strategique", "importance_note": 5, "payment_type": "prélèvement et virement", "invoice_mailbox": "facture", "tva_intracom": "286"}'::jsonb),
  ('SUP-OVH', 'OVH', '30 jours', '{"cost_bracket": "+50 000€", "importance": "strategique", "importance_note": 5, "payment_type": "prélèvement et carte", "invoice_mailbox": "aller chercher", "tva_intracom": "276"}'::jsonb),
  ('SUP-SERVEURCOM', 'SERVEURCOM', '30 jours', '{"cost_bracket": "+50 000€", "importance": "strategique", "importance_note": 5, "payment_type": "prélèvement", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-BECLOUD', 'BE CLOUD', '30 jours FdM', '{"cost_bracket": "+50 000€", "importance": "strategique", "importance_note": 5, "payment_type": "prélèvement", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-SARLOKTEY', 'SARL OKTEY', '30 jours FdM', '{"cost_bracket": "10 000€ - 50 000€", "importance": "important", "importance_note": 4, "account_number": "401OKT", "payment_type": "virement / prélèvement", "invoice_mailbox": "compta"}'::jsonb),
  ('SUP-EBPINFORMATIQU', 'EBP INFORMATIQUE', '30 jours FdM', '{"cost_bracket": "10 000€ - 50 000€", "importance": "important", "importance_note": 4, "payment_type": "prélèvement", "invoice_mailbox": "regarder vers boite contact idem dedibox", "tva_intracom": "285"}'::jsonb),
  ('SUP-OCTOPUS', 'OCTOPUS', 'virement automatique (demander la date à clement )', '{"cost_bracket": "10 000€ - 50 000€", "importance": "important", "importance_note": 4, "payment_type": "virement", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-INGRAM', 'INGRAM', 'Virement pour le cloud et prelevement pour le materiel', '{"cost_bracket": "10 000€ - 50 000€", "importance": "important", "importance_note": 4, "payment_type": "prélèvement, virement et carte", "invoice_mailbox": "facture", "tva_intracom": "291"}'::jsonb),
  ('SUP-GUILLAUMESOURI', 'GUILLAUME SOURISSEAU', 'aléatoire', '{"cost_bracket": "10 000€ - 50 000€", "importance": "important", "importance_note": 4, "payment_type": "virement", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-CIDIT', 'CID-IT', 'immédiat on ne peut pas passer à 30 jours à redemander quand même ,,,,', '{"cost_bracket": "10 000€ - 50 000€", "importance": "important", "importance_note": 4, "payment_type": "virement et carte", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-3CX', '3CX', 'immédiat demanderà  passer à 30 jours à redemander quand même ,,,,', '{"cost_bracket": "10 000€ - 50 000€", "importance": "important", "importance_note": 4, "payment_type": "carte", "invoice_mailbox": "à rajouter boite mail compta (demander à laurent - rajouter un utilisateur facture en admin)+"}'::jsonb),
  ('SUP-AMAZON', 'AMAZON', 'immédiat', '{"cost_bracket": "10 000€ - 50 000€", "importance": "important", "importance_note": 4, "payment_type": "prélèvement", "invoice_mailbox": "aucune on doit les telecharger"}'::jsonb),
  ('SUP-ALSO', 'ALSO', '30 jours fin de mois', '{"cost_bracket": "10 000€ - 50 000€", "importance": "important", "importance_note": 4, "payment_type": "prélèvement", "invoice_mailbox": "facture", "tva_intracom": "277"}'::jsonb),
  ('SUP-DEXXON', 'DEXXON', '30 jours FdM', '{"cost_bracket": "10 000€ - 50 000€", "importance": "important", "importance_note": 4, "payment_type": "prélèvement", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-AUDITCONSEILEX', 'AUDIT CONSEIL EXPERTISE', '30 jours', '{"cost_bracket": "5 000€ - 10 000€", "importance": "standard", "importance_note": 3, "account_number": "401AUD", "payment_type": "prélèvement", "invoice_mailbox": "a rechercher , demander à les envoyer à factures"}'::jsonb),
  ('SUP-APOGEA', 'APOGEA', 'FDM 30/', '{"cost_bracket": "5 000€ - 10 000€", "importance": "standard", "importance_note": 3, "payment_type": "virement", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-ATHENAGLOBALSE', 'ATHENA GLOBAL SERVICES', '15 jours, FDM30', '{"cost_bracket": "5 000€ - 10 000€", "importance": "standard", "importance_note": 3, "payment_type": "prélèvement et virement", "invoice_mailbox": "facture", "tva_intracom": "278"}'::jsonb),
  ('SUP-SYNOLOGY', 'SYNOLOGY', 'immédiat FDM30 c2', '{"cost_bracket": "5 000€ - 10 000€", "importance": "standard", "importance_note": 3, "payment_type": "prélèvement", "invoice_mailbox": "facture", "tva_intracom": "279"}'::jsonb),
  ('SUP-SAGECIEL', 'SAGE CIEL', '244', '{"cost_bracket": "5 000€ - 10 000€", "importance": "standard", "importance_note": 3, "payment_type": "prélèvement", "tva_intracom": "271"}'::jsonb),
  ('SUP-AUDITCONSEILRE', 'AUDIT CONSEIL REZE', '30 jours FdM', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "account_number": "401AUR", "payment_type": "prélèvement"}'::jsonb),
  ('SUP-UBIQUITI', 'UBIQUITI', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte", "invoice_mailbox": "changer la redirection de la facture vers facture"}'::jsonb),
  ('SUP-EDOX', 'EDOX', '30 jours', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "prélèvement", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-TOTALENERGIE', 'TOTAL ENERGIE', '15 jours demander FDM30 jours', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "prélèvement"}'::jsonb),
  ('SUP-GLOBALSIGNGMO', 'GLOBALSIGN GMO', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "virement et carte", "invoice_mailbox": "a chercher", "tva_intracom": "292"}'::jsonb),
  ('SUP-SSTRNSERVICEDE', 'SSTRN (Service de Santé au Tra', '30 jours', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "virement", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-WATSOFT', 'WATSOFT', '30 jours', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "prélèvement", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-MUSCADE', 'MUSCADE', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "virement", "invoice_mailbox": "demander d''envoyer les factures à facture@astorya,fr"}'::jsonb),
  ('SUP-SEWANCOMMUNICA', 'SEWAN COMMUNICATIONS', '15 jours demander FDM30 jours', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "prélèvement", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-AGLO', 'AGLO', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "virement"}'::jsonb),
  ('SUP-AUTODESK', 'AUTODESK', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-MONDAY', 'MONDAY', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte", "invoice_mailbox": "demander d''envoyer les factures à facture@astorya,fr 1x par an"}'::jsonb),
  ('SUP-TELAVOX', 'TELAVOX', 'aléatoire :demander 30 jours fin de mois', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "prélèvement", "invoice_mailbox": "facture", "tva_intracom": "289"}'::jsonb),
  ('SUP-ALIBABA', 'ALIBABA', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-EMERAUDEPROPRE', 'EMERAUDE PROPRETE', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "virement", "invoice_mailbox": "demander d''envoyer les factures à facture@astorya,fr"}'::jsonb),
  ('SUP-PASSBOLT', 'PASSBOLT', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-FREEPRO', 'FREE PRO', '30 jours FdM', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "prélèvement", "invoice_mailbox": "facture", "tva_intracom": "280"}'::jsonb),
  ('SUP-DKV', 'DKV', '15 jours demander FDM30 jours', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "prélèvement", "invoice_mailbox": "facture depuis service compta"}'::jsonb),
  ('SUP-ALLIANCEDUNUME', 'ALLIANCE DU NUMERIQUE', '30 jours', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "prélèvement et virement", "invoice_mailbox": "demander d''envoyer les factures à facture@astorya,fr", "tva_intracom": "293"}'::jsonb),
  ('SUP-MARCEACONSEIL', 'MARCEA CONSEIL', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "virement"}'::jsonb),
  ('SUP-SOFTVALUE', 'SOFT VALUE', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "prélèvement et carte", "invoice_mailbox": "demander d''envoyer les factures à facture@astorya,fr"}'::jsonb),
  ('SUP-OLIVIERASSURAN', 'OLIVIER ASSURANCES', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte", "invoice_mailbox": "demander d''envoyer les factures à facture@astorya,fr"}'::jsonb),
  ('SUP-CDISCOUNT', 'CDISCOUNT', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte", "invoice_mailbox": "demander d''envoyer les factures à facture@astorya,fr"}'::jsonb),
  ('SUP-LDLC', 'LDLC', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte", "invoice_mailbox": "demander d''envoyer les factures à facture@astorya,fr"}'::jsonb),
  ('SUP-PRESTASHOP', 'PRESTASHOP', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-CDKAVOCAT', 'CDK AVOCAT', '15 jours', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "virement", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-CRISRESEAUXSEC', 'CRIS RESEAUX & SECURITE', 'immédiat fdm30', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "virement", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-SOSH', 'SOSH', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "prélèvement", "invoice_mailbox": "demander d''envoyer les factures à facture@astorya,fr"}'::jsonb),
  ('SUP-ENIFORMATION', 'ENI FORMATION', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "virement", "invoice_mailbox": "demander d''envoyer les factures à facture@astorya,fr"}'::jsonb),
  ('SUP-MANATEL', 'MANATEL', 'immédiat fdm30', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "prélèvement", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-NANTEST', 'NANT''EST', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "virement"}'::jsonb),
  ('SUP-ORANGE', 'ORANGE', 'Bonjour,', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "prélèvement"}'::jsonb),
  ('SUP-RDPSOFT', 'RDPSOFT', '244', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-FACTORIAL', 'FACTORIAL', 'Pouvez-vous m’envoyer le Grand Livre des paiements et factures 2025 et 2024 ?', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "prélèvement", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-LAPOSTE', 'LAPOSTE', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "prélèvement et carte"}'::jsonb),
  ('SUP-SENECTIC', 'SENECTIC', 'En vous remerciant,', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-CENTREAUTONANT', 'CENTRE AUTO NANTES', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-EBAY', 'EBAY', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-TRADEMOS', 'TRADEMOS', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "virement"}'::jsonb),
  ('SUP-SOFT4EUROPE', 'SOFT 4 EUROPE', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "virement et carte", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-BROTHER', 'BROTHER', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "virement", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-BUREAUVALLEE', 'BUREAU VALLEE', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-STUDIOCALL', 'STUDIOCALL', '30 jours', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-INDEED', 'INDEED', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-CIDEMA', 'CIDEMA', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "virement"}'::jsonb),
  ('SUP-WPALLIMPORT', 'WP ALL IMPORT', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-LEDEBOUCHEUR', 'LE DEBOUCHEUR', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "virement"}'::jsonb),
  ('SUP-OBOCK', 'OBOCK', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-MAILJET', 'MAILJET', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte", "invoice_mailbox": "demander d''envoyer les factures à facture@astorya,fr"}'::jsonb),
  ('SUP-GRAVITYFORMS', 'GRAVITY FORMS', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-GENERALI', 'GENERALI', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "invoice_mailbox": "demander d''envoyer les factures à facture@astorya,fr"}'::jsonb),
  ('SUP-IBIS', 'IBIS', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-FEUVERT', 'FEU VERT', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-ONOFFTELECOM', 'ONOFF TELECOM', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-DUPLICATOR', 'DUPLICATOR', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-AGIRRECOUVREME', 'AGIR RECOUVREMENT', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "virement", "invoice_mailbox": "demander d''envoyer les factures à facture@astorya,fr"}'::jsonb),
  ('SUP-CONTROLETECHNI', 'CONTROLE TECHNIQUE OUEST', '15 jours', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-RKTECH', 'RK TECH', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-EDOC', 'EDOC', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "prélèvement"}'::jsonb),
  ('SUP-ELECLERC', 'E.LECLERC', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-ELEMENTOR', 'ELEMENTOR', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte", "invoice_mailbox": "demander d''envoyer les factures à facture@astorya,fr"}'::jsonb),
  ('SUP-AXA', 'AXA', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2}'::jsonb),
  ('SUP-CANVA', 'CANVA', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-ENVATO', 'ENVATO', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-GREFFEDUTRIBUN', 'GREFFE DU TRIBUNAL DE COMMERCE', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "virement", "invoice_mailbox": "282"}'::jsonb),
  ('SUP-ONTHEGOSYSTEM', 'ON THE GO SYSTEM', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-ATELIERPORTABL', 'ATELIER PORTABLE', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-ADAPTATEURPC', 'ADAPTATEUR-PC', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-MICROSOFT', 'MICROSOFT', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-CASTORAMA', 'CASTORAMA', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-ALIEXPRESS', 'ALIEXPRESS', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte", "invoice_mailbox": "demander d''envoyer les factures à facture@astorya,fr"}'::jsonb),
  ('SUP-LIFEAZ', 'LIFEAZ', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "prélèvement"}'::jsonb),
  ('SUP-COMPLIANZ', 'COMPLIANZ', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-WPMDIA', 'WP Média', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-DRISTELLAR', 'DRI STELLAR', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2}'::jsonb),
  ('SUP-NETLYON', 'NET LYON', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2}'::jsonb),
  ('SUP-3PP', '3PP', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2}'::jsonb),
  ('SUP-RUEDUCOMMERCE', 'RUE DU COMMERCE', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2}'::jsonb),
  ('SUP-REMARKABLEAS', 'REMARKABLE AS', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte", "invoice_mailbox": "demander d''envoyer les factures à facture@astorya,fr"}'::jsonb),
  ('SUP-ADOBE', 'ADOBE', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "invoice_mailbox": "demander d''envoyer les factures à facture@astorya,fr"}'::jsonb),
  ('SUP-OSCARO', 'OSCARO', 'immédiat', '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "carte"}'::jsonb),
  ('SUP-EASYTEO', 'EASYTEO', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "virement", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-MAILINBLACK', 'MAILINBLACK', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "payment_type": "virement", "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-KOESIO', 'KOESIO', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "invoice_mailbox": "demander d''envoyer les factures à facture@astorya,fr"}'::jsonb),
  ('SUP-TEAMVIEWER', 'TEAM VIEWER', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "invoice_mailbox": "facture demander à laurent si non recu"}'::jsonb),
  ('SUP-LOCAM', 'LOCAM', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2, "invoice_mailbox": "facture"}'::jsonb),
  ('SUP-HOPLA', 'HOPLA', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2}'::jsonb),
  ('SUP-SOFTCONNECT', 'SOFT CONNECT', NULL, '{"cost_bracket": "-5 000€", "importance": "secondaire", "importance_note": 2}'::jsonb)
ON CONFLICT (name) DO UPDATE SET
  payment_terms = COALESCE(NULLIF(EXCLUDED.payment_terms,''), suppliers.payment_terms),
  data = suppliers.data || EXCLUDED.data,
  updated_at = now();
